{"name": "创建英雄_test_create_hero_power_fail", "status": "broken", "statusDetails": {"message": "TypeError: '<=' not supported between instances of 'str' and 'int'", "trace": "self = <test_game_by_data.test_create_hero.Test_hero object at 0x0000015A4C2F2D10>\npower = 'e'\n\n    @allure.title(\"创建英雄_test_create_hero_power_fail\")\n    @pytest.mark.FAIL\n    @pytest.mark.parametrize(\"power\", LoadUtils.loadData(\"test_hero_create.yaml\")[\"power_fail\"], ids=[\"战斗力_fail_0\", \"战斗力_fail_-1\", \"战斗力_fail_0.001\", \"战斗力_fail_e\"])\n    def test_create_hero_power_fail(self, power):\n        hero_management = HeroManagement()\n>       hero_management.create_hero(\"power_fail\", 20, power)\n\ntest_create_hero.py:64: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <game.hero_management.HeroManagement object at 0x0000015A4C338A10>\nhero_name = 'power_fail', hero_volume = 20, hero_power = 'e'\n\n    def create_hero(self, hero_name, hero_volume, hero_power):\n        if hero_volume<=0 or hero_volume >= 100:\n            return False\n>       if hero_power <=0:\nE       TypeError: '<=' not supported between instances of 'str' and 'int'\n\n..\\game\\hero_management.py:34: TypeError"}, "parameters": [{"name": "power", "value": "'e'"}], "start": 1684677423639, "stop": 1684677423639, "uuid": "222fc01a-22b5-47d9-8fec-07fe48a29847", "historyId": "f7cdd780ea4d381552d5a803c8fc7051", "testCaseId": "df7f1128f803173742f89a41135b0851", "fullName": "test_create_hero.Test_hero#test_create_hero_power_fail", "labels": [{"name": "tag", "value": "FAIL"}, {"name": "suite", "value": "test_create_hero"}, {"name": "subSuite", "value": "Test_hero"}, {"name": "host", "value": "WIN-20230414OLX"}, {"name": "thread", "value": "14340-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_create_hero"}]}